pipeline {
    agent any
    stages {
        stage('Build calculator') {
            steps {
                bat 'mvn -f .\\calc\\pom.xml clean package'
            }
        }
        stage('Test') {
            steps {
                bat 'mvn -f .\\calc\\pom.xml test'
            }
        }
        stage('Collect artifacts') {
            steps {
                archiveArtifacts 'calc/backend/target/*.jar'
            }
        }
    }
}